### ISSUE TITLE
A First Release and some context

### ISSUE THREAD

**Issue by robertpsoane** [robertpsoane/ducker#2]
I have inexplicably got home from work to find a bunch of stars and a fork of `ducker`, as well as a request for a license to be added!

This started as a "lets learn a bit more rust" and I thought of "k9s for docker" as a fist project idea.

Over the past few weeks I've hacked together the first steps towards the "k9s for docker" TUI app, and have decided to rush out a tag/release to allow the various people who have happened across the project to try it out simply (and to "claim" my name on crates.io - I love the name ducker! ASCII-art ducks incoming at some point!)

There isn't currently any CI or automated release, nor have I given any serious thought to distributing binaries, but I've got an initial set of features I'd like to add [here](https://github.com/robertpsoane/ducker/blob/325f92c298cf6bcd08c0dfb3d416634eba567fd8/ISSUES.md).

I'd love any feedback or ideas for things to add etc, so please do share them!

**Comment by orhun** [comment]
Hey, thanks for sharing your retrospective & ideas about this awesome project! 🦆 

> I have inexplicably got home from work to find a bunch of stars and a fork of ducker

I might have something to do with it, since it's been posted on [Ratatui socials](https://x.com/orhundev/status/1806282786547937459) :)

> but I've got an initial set of features I'd like to add [here](https://github.com/robertpsoane/ducker/blob/325f92c298cf6bcd08c0dfb3d416634eba567fd8/ISSUES.md).

This looks pretty good to me. I think `ducker` has a lot of potential when it comes to becoming a "container management framework" of some sort.

For some inspiration, I recommend checking out [oxker](https://github.com/mrjackwills/oxker) which is in the same field as `ducker`.

I will be watching closely and might contribute (e.g. CI/automation) things. The future is exciting! 🚀

**Comment by robertpsoane** [comment]
> I might have something to do with it, since it's been posted on [Ratatui socials](https://x.com/orhundev/status/1806282786547937459) :)

Ahh thanks very much!

> For some inspiration, I recommend checking out [oxker](https://github.com/mrjackwills/oxker) which is in the same field as ducker.

I will take a look!
